### ISSUE TITLE
Can't find what we did in class

### ISSUE THREAD

**Issue by LuukAlards1** [janboone/programming_for_economists#2]
Well the title explains the issue I'm having.
The jupyter page I get makes no sense to me and I'm worried I'm messing it up completely.
And because I'm technically a repeater, I don't know if I did things correctly with DataCamp.

Kind regards,

Luuk Alards

**Comment by janboone** [comment]
I don't understand what you mean by "The jupyter page I get makes no sense to me".

All relevant information about datacamp, exam, schedule, how to get the assignments on the russet server can be found here: https://janboone.github.io/programming_for_economists/pages/schedule/

The rules for repeaters are the same as for students doing this for the first time. So read the webpages carefully; especially the part about the exam.
