### ISSUE TITLE
Datacamp progress not saved. 

### ISSUE THREAD

**Issue by engbersB** [janboone/programming_for_economists#5]
Hi, 
I have to work remotely for 90% and am therefore very dependent on datacamp to make sure I learn. On 28th jan when I started in on jupyter assignment 1 I realised I needed intruction and went to datacamp.  Returning today I realize it did not save my progress (or XP) in the course at all on datacamp, although in jupyter it did. Is this normal?

**Comment by janboone** [comment]
I am not sure I understand the problem. Just to be sure: for the course your progress on Datacamp is not relevant.

What do you mean that in jupyter your progress was saved? You datacamp progress?

**Comment by engbersB** [comment]
Good afternoon,

No i just noticed that in datacamp the xp was not saved. I thought it was
used in addition to jupyter to record progress and it would have been
faster for me to check in and out of the content. But i will just make a
note on my desk instead.

Kind regards,
Britt
