### ISSUE TITLE
In-class notebook issue

### ISSUE THREAD

**Issue by NikolayPavlov98** [janboone/programming_for_economists#9]
Hello, I have a problem with the notebook that we did during the tutorial. In the first screenshot, I asked my tutorial teacher if I did it correctly and he modified it a bit and said its alright. But after that, the built-in code which im suppost to run keeps giving me an error and I do not why. Can you check it out please? Thank you very much
I attached pictures of the problem
![Problem_1](https://user-images.githubusercontent.com/47292486/54979983-dc412b00-4fa4-11e9-88c0-662d2857a9e0.JPG)                
![Problem_2](https://user-images.githubusercontent.com/47292486/54980009-ea8f4700-4fa4-11e9-88c3-c1b32e14e423.JPG)
![Problem_3](https://user-images.githubusercontent.com/47292486/54980018-f0852800-4fa4-11e9-8a71-abe9191552cd.JPG)

**Comment by janboone** [comment]
under c) you define the variable `number_of_customers`, but this is not part of the dataframe `df_customers`. Therefore, you get an error saying the key (variable) `number_of_customers` cannot be found in `df_customers`.

Change the code under c) to: `df_customers['number_of_customers'] = np.exp(...)`

Then it should work.

**Comment by NikolayPavlov98** [comment]
That worked, thank you very much!
I have another issue with the class notebook in week 2
![Error](https://user-images.githubusercontent.com/47292486/55015866-f5ba9500-4fed-11e9-90f9-f5156f59617a.JPG)
Could you show me the correct way of doing the profits? Thank you

**Comment by janboone** [comment]
`costs` and `q` are variables/columns in the dataframe. You refer to them as `df_simulations['costs']` and `df_simulations['q']`.

Does this help?

**Comment by NikolayPavlov98** [comment]
It did, I understand it better now.
But im still getting an error
![Error_2](https://user-images.githubusercontent.com/47292486/55023667-9bc1cb80-4ffd-11e9-832c-ee093a3613e1.JPG)
